### ISSUE TITLE
Make program availability updatable

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#108]
Make endpoint to get/post/update data for program availability 

- data can be updated with some regularity

- data informs queue availability on front end by not allowing user to add individuals to a queue after program end time on a given day

**Comment by MikeyManoguerra** [comment]
I'm working on this

**Comment by hhummel** [comment]
Hey Mikey, 

Are you changing the Service model in addition to doing the serializer and the view?  My suggestion is to add a start time and end time to the Service model object so show when the service is on, and use the existing "available" field to signify that the service isn't overloaded and it's okay to put more participants in the queue.

I would then compare with the time-of-day and check the "available" field to determine if new participants could be checked in.  I would put that logic in the view, although it could reside in the frontend too. 

Let me know if I can help

**Comment by mariekers** [comment]
How do we manage updating program availability between the front end, the is_closed flag in the visit, and the program availability table?

**Comment by mariekers** [comment]
@Nkdiaz would you be interested in picking this one up?

**Comment by mariekers** [comment]
@mattusifer would you want to work on this?

**Comment by mattusifer** [comment]
Sure thing

**Comment by mariekers** [comment]
@mattusifer you still interested?

**Comment by mattusifer** [comment]
@mariekers Seems like the remaining scope of this issue is to prevent adding users to the queue if the current time is outside of the target program's availability, is that correct? I can make that change if so.

**Comment by mariekers** [comment]
@mattusifer I think this is covered by the [freeze program](https://github.com/CodeForPhilly/prevention-point/pull/224) updates - what do you think?  Do those updates need to integrate with the program hours?
