### ISSUE TITLE
Populate Program Availability table

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#111]
Create fake data for program hours sunday through saturday

**Comment by mariekers** [comment]
Should match all programs in the HRSC sign in [sheet](https://docs.google.com/spreadsheets/d/1FXWwucFs3mtfgIR3GksoxMnCkyNyvtU4hVQSoBtkG18/edit?usp=sharing)

**Comment by quinn-dougherty** [comment]
the relevant document is `core/management/commands/seed.py`. 

The hyperlinked sheet requires permissions. 

i'll start on this as soon as i have access to the sheet

**Comment by quinn-dougherty** [comment]
https://github.com/CodeForPhilly/prevention-point/pull/216
