### ISSUE TITLE
Input Note Modal

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#123]
**User Story:**
As a Front Desk Employee (FDE), I need to be able to input a note about a participant, so that I can better manage the waitlist and inform the providers. #131 

**AC:**
- [ ] From the waitlist page, when clicking the Note icon next to a participants name, a modal should pop up that allows a user to input a note
    - Images:  
        - https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=2%3A18
        - https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=366%3A19545
        - https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=373%3A19734
- [ ] An icon should appear on the waitlist to indicate when a note is associated with a participant
    - Image: https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=21%3A798

**Comment by kyle-hauber** [comment]
10.8 Notes
Needs tests. If not updated by next week, will move to James to close out if time permits.

**Comment by jkeary** [comment]
https://github.com/CodeForPhilly/prevention-point/wiki/Front-End-Automated-Testing
