### ISSUE TITLE
Enable searching by Prevention Point ID

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#126]
Need to be able to search by the PPID, NOT the database ID

Can already search by First Name and Last Name and need to retain this functionality

**Comment by jkeary** [comment]
Just fyi, this is a blocking ticket for completion of ticket [81](https://github.com/CodeForPhilly/prevention-point/issues/81)

**Comment by jkeary** [comment]
sorry, didnt mean to close this...
