### ISSUE TITLE
Include service in the queue api

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#127]
Include service in the queue api - this enables the waitlist to easily contain all of the available PP services

**Comment by hhummel** [comment]
I will add Service to the Visit model as part of this ticket

**Comment by MikeyManoguerra** [comment]
Im doing this through issue #132

**Comment by mariekers** [comment]
@MikeyManoguerra currently working on this

**Comment by mariekers** [comment]
Blocked until #132 is done

**Comment by mariekers** [comment]
#132 is now done - is service also in the queue api?  @MikeyManoguerra ?

**Comment by MikeyManoguerra** [comment]
@mariekers  sorry i do not notifications anywhere for github, i gotta fix that.  Yes this is done!
