### ISSUE TITLE
SPIKE: Research automated testing on FE

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#128]
*User Story*
As a Code for Philly engineer, I want automated Front End testing so that I know my PRs will pass.

*Acceptance Criteria*
- [x] Completion of this issue required a proposed framework for implementing automated testing that will review PRs for issues.
- [x] Provide options to better evaluation the different ways we can implement testing (ex: high, medium, low LOE approaches)

*Considerations*
Github has a new CICD tool.  What other ways can we implement

**Comment by jkeary** [comment]
I havent had a chance to look into this yet, however, I read a bit about Jest for automated testing of react components and I think this is the way to go.

**Comment by kyle-hauber** [comment]
@jkeary - Marieke mentioned that she though you were working on this now, so I've moved it to in-progress.  If you haven't though, could you please let me know?  I can move it back to the backlog

**Comment by jkeary** [comment]
you can keep it in progress, Im working on it concurrently to my other tickets

**Comment by jkeary** [comment]
jest docs: https://jestjs.io/en/

enzyme docs: https://airbnb.io/enzyme/docs/api/

branch: Automated_Testing_128

**Comment by jkeary** [comment]
run tests using `yarn test`

**Comment by jkeary** [comment]
https://github.com/CodeForPhilly/prevention-point/wiki/Front-End-Automated-Testing

**Comment by mariekers** [comment]
Enforce having these tests on all front end PRs going forward - will need merging of branch `automated_testing_128` to master

**Comment by mariekers** [comment]
@jkeary will create a new branch and put tests on it, will do quick PR (testing one component) to ensure that they are working as planned

**Comment by jkeary** [comment]
pr approved, closing
