### ISSUE TITLE
No "urgency" or "service" fields in Visits model. No insurance information on Participant.

### ISSUE THREAD

**Issue by hhummel** [CodeForPhilly/prevention-point#132]
Checkin Entry Form #85 captures the urgency and service associated with the visit, and this information is shown in Waitlist Homepage #86. But there is no field capturing this (these?) data in the Visit model. 

My suggestion is to add the "urgency" field, switch the "program" to "service", (provided service implies program), and then include both urgency and service in the queue view. 

There's also no insurance field in Participant. Perhaps there should be an Insurance model at some point?

**Comment by MikeyManoguerra** [comment]
I am working on program-service mapping for visit model

**Comment by mariekers** [comment]
Check to see if there are any other missing fields between the design and the current back end

**Comment by mariekers** [comment]
Service & urgency on visit (@MikeyManoguerra )
Insurance & insurance status on participant (@hhummel )

**Comment by kyle-hauber** [comment]
@MikeyManoguerra , @hhummel  - The attached PR is merged and closed.  Can we call this story complete?

**Comment by MikeyManoguerra** [comment]
@kyle-hauber  the 'urgency' and 'service' parts on this issue are completed

**Comment by MikeyManoguerra** [comment]
@kyle-hauber  looks like #141 covers the insurance portion of this. i think it can be closed

**Comment by mariekers** [comment]
I know @MikeyManoguerra and @hhummel were both working on this - any status updates?
