### ISSUE TITLE
Check UPDATE api function

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#142]
Ensure that updating data in front end makes update call to api.

**Comment by marcelkooi** [comment]
@rlacon Are you still working on this?

**Comment by rlacon** [comment]
@marcelkooi I'm running into an error when submitting data and can't figure out what's wrong, so I'm having James help me with the issue.

**Comment by marcelkooi** [comment]
> @marcelkooi I'm running into an error when submitting data and can't figure out what's wrong, so I'm having James help me with the issue.

Sounds good, let me know if more assistance is needed. Also, do you mind pushing up a PR for this to get more visibility?

**Comment by mariekers** [comment]
@rlacon - any updates?

**Comment by hhummel** [comment]
The updates work from QueueTable. The remaining question is getting them working from the Participant screen
