### ISSUE TITLE
Empty queue error message

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#143]
Update empty queue error message - stop displaying 404 error

Done

- [ ] empty queue message: "queue is empty"

**Comment by mattusifer** [comment]
@mariekers I've opened a PR (#151) to return an empty array instead of a 404 for an empty queue. The front end will need to be updated to display the "queue is empty" message if the response is empty.

**Comment by mariekers** [comment]
Added FE issue to resolve - thanks for the heads up, Matt!
