### ISSUE TITLE
update program-service map table 

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#144]
Program-service mapping needs to be able to handle:

- [ ] new services
- [ ] new programs
- [ ] label inactive program-services

Add logic to posted programs/services to create corresponding row/map/object

**Comment by MikeyManoguerra** [comment]
@mariekers  this is not vital for MVP, but obviously important. Where will admins update this type of information? in the admin ? or are we building admin react stuff

**Comment by mariekers** [comment]
table deprecated
