### ISSUE TITLE
Urgency field

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#145]
Urgency needs to be added to:

- [ ] participant detail page
- [x] queue table

**Comment by marcelkooi** [comment]
Isn't it already on the queue table or do we need to modify this column?

<img width="261" alt="Screen Shot 2019-10-26 at 2 34 41 PM" src="https://user-images.githubusercontent.com/13142719/67624373-c5dea480-f7fd-11e9-98ba-2d84540f7b95.png">

**Comment by jkeary** [comment]
I think @hhummel has added this to queue table.  But where is Urgency supposed to be on the Participant Info page?  @mariekers?  Right now @crsmyz is working on that page so this ticket could be for him, but I have no idea what needs to be added to that page.  Looking for some clarification from @mariekers

**Comment by hhummel** [comment]
Urgency is shown in QueueTable, but @crsmyz is wrapping the Participant page

**Comment by mariekers** [comment]
added!~
