### ISSUE TITLE
order queue by urgency value/visit created tstamp

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#147]
Automatically order queue by 

1. urgency
2. earlier timestamp

Participants with the same urgency value should be ordered by timestamp.

**Comment by mariekers** [comment]
Queue is currently ordered by logic in the back end

**Comment by mattusifer** [comment]
@mariekers @MikeyManoguerra This feels like a front-end issue. The javascript layer can re-sort whatever data we pass back - and I can imagine eventually adding the ability to apply different sorting to the queue directly within the front end.

**Comment by mariekers** [comment]
@jkeary what are your thoughts?

**Comment by jkeary** [comment]
I think in this case its fine to have sorting on the front since we are passing the entire queues forward.  If the data sets were larger I'd say sorting should be handled on the back end.  But these queues are rather small, right @mariekers ?  Are we going to have selectable sorting options in the UI?

**Comment by mariekers** [comment]
@jkeary I don't think we're going to have that option.  I also don't think queues will have more than 50 people.  Is that small enough?

**Comment by TriStarGod** [comment]
I'll attempt to resolve this on the frontend

**Comment by jkeary** [comment]
@TriStarGod and I discussed with @mariekers, this is really a backend ticket.  So I am moving this to backend tag.  @TriStarGod will take it.  @mariekers Is there a frontend part to this at all?  Like should there be any filters on the queue?

**Comment by TriStarGod** [comment]
Temp fix until urgency field and sort is setup on backend - https://github.com/CodeForPhilly/prevention-point/tree/Issues-147-183

**Comment by hhummel** [comment]
Resolved with update-queues-163
