### ISSUE TITLE
update status options in queue

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#149]
Options should be

- waiting
- stepped out
- left

Current state: 

<img width="331" alt="Screen Shot 2019-10-02 at 2 12 47 PM" src="https://user-images.githubusercontent.com/9036553/66070130-bb8efa80-e51e-11e9-8b28-4c1b0e107a8b.png">

Does the back end need to be updated?

**Comment by hhummel** [comment]
Resolved with update-queues-163
