### ISSUE TITLE
BUG - Refresh the login token

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#153]
**Observed**
When browsing the site, you the backend will not connect after 5 minutes

**Expected**
browsing the site, the backend and frontend functionalities are always hooked up

**Tech Details:**
The token needs to be refreshed automatically

**Comment by marcelkooi** [comment]
@kyle-hauber Do you know who reported this bug? I'm not able to reproduce it. The token seems to refresh correctly

**Comment by jkeary** [comment]
@marcelkooi this ticket has been open so long, I think the first that came from when I started on the project, that I am not even sure it was ever a real thing anymore.  It came out of a conversation that @hhummel and I had about it kicking him out when he was working.  Harry any thoughts?

**Comment by marcelkooi** [comment]
Thanks @jkeary. @hhummel closing this but feel free to open back up if this is still an issue for you.

**Comment by crsmyz** [comment]
I'm still seeing the auth token expiring after 5 minutes in my local. This will be a major blocker before we can get this deployed Tina server.
