### ISSUE TITLE
Add Participant to Queue visit logic

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#154]
once I click 'add to queue', I need to make sure that 

Connecting front end to visits endpoints:
- [x] checking in participants
- [x] updating notes
- [x] updating urgency score (priority level)
- [x] updating status
- [x] updating "seen"

This includes:
Participants Information page 
- [x] add to queue button

Queue page: 
- [x] Notes modal
- [x] Urgency field 
- [x] Status
- [x] Seen 

Misc.
- [x] Create API endpoints
- [x] Create notes store
- [x] Add API unit tests
Once participant is added to queue, status should automatically be set to 'Waiting'

- [x] Re-evaluate need for the notes store.
- [x] Hook up program, services, and insurer APIs to edit participant info page
- [x] confirm that participants will show up in queue and visits pages after proper data editing is made.

**Comment by jkeary** [comment]
https://github.com/CodeForPhilly/prevention-point/wiki/Creating-Front-End-Components

**Comment by crsmyz** [comment]
Should be hitting this project point this week. My weekend was fairly busy but my week is open for this.

**Comment by crsmyz** [comment]
This is officially in progress! :+1:

**Comment by marcelkooi** [comment]
> This is officially in progress! 👍

Awesome! Can you please push up a PR for this? No problem if it's still in progress

**Comment by crsmyz** [comment]
S

> > This is officially in progress! 👍
> 
> Awesome! Can you please push up a PR for this? No problem if it's still in progress

Sure let me get a PR going to hold me to finishing this. Give me a day or two..

**Comment by crsmyz** [comment]
NotesStore has been completed and merged.
Currently working on adding API endpoint tests to visits API.

**Comment by mariekers** [comment]
@crsmyz how's the API coming along? Any blockers?

**Comment by crsmyz** [comment]
@mariekers The API part has been merged but #85 is blocking me for right now since this needs pages that don't exist yet. Working with @jkeary on 85 to get that on track this week or early next week to unblock this.

**Comment by crsmyz** [comment]
New todos on this are.

[] 1. Re-evaluate need for the notes store.
[] 2. Hook up program, services, and insurer APIs to edit participant info page
[] 3. confirm that participants will show up in queue and visits pages after proper data editing is made.
