### ISSUE TITLE
Create/Edit Users 

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#164]
Add functionality for admin users to 

- [ ] search/see all current users
- [ ] update user settings
- [ ] deactivate users 
- [ ] add new users
- [ ] set user roles
- [ ] grant access for external providers (by program)

Depends on #165

**Comment by jkeary** [comment]
@mariekers is there a design for this?

**Comment by jkeary** [comment]
https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=0%3A1

**Comment by mariekers** [comment]
will manage users from django UI
