### ISSUE TITLE
Django User Endpoint Updates

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#165]
System User data is accessible to front end.

User types include:

1. Admin
   - Access to all data and system functionalities
2. Internal Provider
   - Access to all data
3. External Provider
   - Access to program specific data
4. Front Desk
   - Access to searching participant object & modify/update/post check-in objects

**Comment by MikeyManoguerra** [comment]
@mariekers  will different external providers need access to different program infos? if external providers can be considered all the same, we can create a fourth group. if there will be multiple providers each requiring different permissions, will require more thought.

**Comment by mariekers** [comment]
Front desk users can access everything used by the MVP

External providers should be able to access everything the front desk accesses + their program's data

Internal providers can access everything (minus the admin functionalities)

Admins can access everything

**Comment by MikeyManoguerra** [comment]
closing. see #167
