### ISSUE TITLE
Program Availability Hours

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#169]
Object in the back end that stores the start time and end time each program is available each day of the week. 

FK to program table based on program ID

**Comment by MikeyManoguerra** [comment]
This already exists, though it isn't seeded

**Comment by jkeary** [comment]
@mattusifer is going to check if this data is coming from the back end in the queues api

**Comment by MikeyManoguerra** [comment]
Unless @mattusifer has updated this, program availability is only available from its own endpoint, and is not included in the queue. a programs hours does nothing to protect against front desk events/ visits being updated for that program. for now the front end can use the info, and later the back end can protect against it

**Comment by quinn-dougherty** [comment]
https://github.com/CodeForPhilly/prevention-point/pull/216

**Comment by mariekers** [comment]
Does this object have an endpoint?  Should there be a new ticket for it?

**Comment by MikeyManoguerra** [comment]
The object does have an endpoint. `api/programs/<int:program_id>/program-availability/`

**Comment by MikeyManoguerra** [comment]
This ticket can be closed. new functionality can be a new ticket!
