### ISSUE TITLE
Use Program Availability Hours on Front End

### ISSUE THREAD

**Issue by jkeary** [CodeForPhilly/prevention-point#180]
Back end should pass the program availability hours thru the queues api for the front end components to use.  If a queue is not available to sign up for, there should be 2 things that happen on the front.  
- [ ] Queues screen should display that that particular queue is not available for sign up currently.  Need input from UI/UX person (@mariekers )
- [ ] Participants Screen should not allow adding additional signups to the queues.  THere should be a var in the queues store of currently available queues that one can sign up for, and those are what should be displayed on the dropdown of this screen

**Comment by jkeary** [comment]
corresponding backend ticket: https://github.com/CodeForPhilly/prevention-point/issues/169.  Use the api endpoints `api/programs/<int:program_id>/program-availability/` to see if the times are there

**Comment by mariekers** [comment]
closing for now - will reopen when fx is requested by PPP
