### ISSUE TITLE
queue not displaying urgency status & notes

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#183]
Queue on front page not displaying urgency status or notes from back end- need to pull from react component

**Comment by mariekers** [comment]
@hhummel - we're also seeing that the urgency number is a string ('four') - can you update the urgency value to an integer?

**Comment by TriStarGod** [comment]
Made a temp fix for urgency. Easy to revert once urgency field on db is fixed on backend. Notes will now pop up. For the moment, its read only.

**Comment by hhummel** [comment]
Fixed with update-queues-163
