### ISSUE TITLE
Fixing "Participant Search" page to show filtered results.

### ISSUE THREAD

**Issue by crsmyz** [CodeForPhilly/prevention-point#192]
Currently the "ParticipantList" component does not show filtered results for current participants. 

As a user I should be able to search for a participant by ID or by first name and last name and see only results that fit my parameters.

Example:

Search by FL3498.   =>  result, I should see only participants with that ID

Search by Darius Brown => result, I should see only participants with that first and last name.

**Comment by SeanCLynch** [comment]
Not super experienced with recent evolutions of react, but around [here](https://github.com/CodeForPhilly/prevention-point/blob/d923fc48622bf0d2125e686fe565b80a2aa7ad94/frontend/src/components/UserSearch.js#L54) it looks like there is an `onSubmit` handler in addition to an `onChange` handler for this form. Perhaps they are somehow interfering with each other?
