### ISSUE TITLE
"General Services" returns to queue page

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#208]
<img width="350" alt="Screen Shot 2020-01-22 at 5 18 50 PM" src="https://user-images.githubusercontent.com/9036553/72939651-49dff400-3d3b-11ea-870a-b5c7387b0cd1.png">

Clicking on the general services logo returns user to queue page (home page)

**Comment by marcelkooi** [comment]
What's supposed to happen if you click on it?

**Comment by mariekers** [comment]
Sorry, @marcelkooi - didn't see the question. 

It's supposed to return you to the home page

**Comment by mariekers** [comment]
@marcelkooi did you work on this?

**Comment by marcelkooi** [comment]
@mariekers I didn't, but it's an easy fix and I can work on it
