### ISSUE TITLE
dockerize front end 

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#212]
Project needs to be fully dockerized

Done: front end component added to docker-compose

**Required to host in linode

**Comment by ThrowsException** [comment]
I might be able to help with this. What would the container actually need to provide to be usable by linode? Something like an nginx container with ports exposed serving the frontend assets or just a container with the assets built in folders?

**Comment by mariekers** [comment]
@ThrowsException I'm going to direct this to @themightychris

**Comment by mariekers** [comment]
the main issue here is to add the front end to the docker-compose file as a second service

**Comment by themightychris** [comment]
Please expose an HTTP port from the container. CfP ops will handle putting SSL in front of it

**Comment by hhummel** [comment]
@ThrowsException are you working on this?

**Comment by ThrowsException** [comment]
@hhummel hey sorry Ive been away for a few days I was hoping to jump on this today. Shouldnt be to long to get a working nginx container up

**Comment by mariekers** [comment]
@ThrowsException is this done?

**Comment by ThrowsException** [comment]
@mariekers Ive merged in @themightychris changes to the PR awaiting review.

**Comment by themightychris** [comment]
It was good to go in my book pending that merge, just marked the PR approved, are we waiting on anyone else?

**Comment by ThrowsException** [comment]
@themightychris I don't think so. I think its just been me you and @mariekers. Want me to merge?

**Comment by themightychris** [comment]
![giphy (1)](https://user-images.githubusercontent.com/458494/75407285-98575400-58e0-11ea-8fbc-2f91656e615d.gif)
