### ISSUE TITLE
Open participant detail page from queue

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#213]
As a front desk employee, i want to be able to see & modify user details for a participant in the queue (includes updating program & service information for a visit). 

Clicking on participant in queue should direct user to participant detail page for that participant.  User should be able to change any field except UUID on the page. 

@MikeyManoguerra - how can we edit visit information on the participant detail page?  Is there an available MODIFY call for the visit endpoint?

**Comment by mariekers** [comment]
@hhummel @crsmyz I know y'all were working on this - mind assigning yourself/updating the issue?

**Comment by crsmyz** [comment]
Donezo!
