### ISSUE TITLE
temporarily "freeze" queue

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#214]
As a provider, I want to be able to temporarily stop the front desk from adding new people to a queue. 

Done: add button/check box to queue page to stop *that* queue - stop button should be relative to active queue tab

**Comment by ThrowsException** [comment]
Unsure of the requirements here. To me it seems people are added to queues by visiting the /participantInfo endpoint and filling out the information and specifying the queue (Program?). 

Seems like the update here if im reacding it right is the backend needs to know which queues are "active" and only display programs in the drop down that a hold has not been placed which would require some backend work as well.

**Comment by mariekers** [comment]
Excellent question, @ThrowsException 

Providers need to be able to tell the person at the front desk to temporarily stop adding participants to the queue, so they need the ability to 
 - [ ] mark a program as temporarily frozen from the queue page
 - [ ] program is unavailable in dropdown on participant detail page
 - [ ] provider can "unfreeze" a program from the queue page

This probably has front and back end work - I'd love to hear your thoughts on the best way to implement this!

**Comment by MikeyManoguerra** [comment]
This is finished!
