### ISSUE TITLE
Login form provides no feedback when username/password is incorrect

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/prevention-point#229]
A clear error message should be displayed to the user when the provided username or password is invalid

**Comment by crsmyz** [comment]
@angelyoung24 would you like to work together on this issue? We can do a screen share meeting to get on the same page and figure out how to approach it.

**Comment by angelyoung24** [comment]
@crsmyz Yes. Ping me on Slack so we can arrange something.

**Comment by crsmyz** [comment]
@themightychris @mariekers Do we have requirements on what a valid username and password should be?

**Comment by themightychris** [comment]
@crsmyz this issue isn't related to a registration step where a user would be choosing a username/password, it is about the login form just sitting there and providing zero feedback when you enter a username+password for login that gets rejected

**Comment by angelyoung24** [comment]
@themightychris So it's like, for example, a HTML form validation except with Material-UI?

**Comment by themightychris** [comment]
@angelyoung24 no, this isn't form validation at all, it's handling the server response to incorrect username+password combinations by adding an error message to the page. It is not possible to check the validity of the username+password within the form, they have to be sent to the server to be checked against the user database

**Comment by angelyoung24** [comment]
@themightychris Would this be a good first time issue? It seems a bit complex...

**Comment by angelyoung24** [comment]
Meaning I am not experienced in back end so I don't understand why I was recommended this issue to begin with.

**Comment by themightychris** [comment]
Yes it's a good first issue, the work to be done is entirely frontend. There's already a spot in the frontend code where it's sending the login to the server and then evaluating the response. When the server says success it's sending you to the next screen, and when the server says failure it's currently doing nothing. Instead of doing nothing, it needs to tell the user that their login was incorrect, maybe through a modal alert, a toast alert, or an inline error message within the form

**Comment by mariekers** [comment]
We just need a dialogue box to appear saying that the username/password doesn't work.

**Comment by themightychris** [comment]
This existing TODO line in where you know the login failed: https://github.com/CodeForPhilly/prevention-point/blob/master/frontend/src/stores/AuthStore.js#L36

That line needs to, through an exception or return value or an event however you're supposed to communicate a result from a store operation back out to the UI with mobx get that happening back out to the login form component: https://github.com/CodeForPhilly/prevention-point/blob/master/frontend/src/components/LoginForm.js#L26

So it can show something to the user somehow. If there are any forms in the app already that can fail a submit with a server-side error and then indicate that failure to the user somehow, that's probably a pattern to replicate here

**Comment by crsmyz** [comment]
@angelyoung24 this demo  from Material UI should help as well, they outline error state example for different fields. You can bind this to the API call being made to verify the username and password and display on an error.

https://codesandbox.io/s/3zv7l

**Comment by mariekers** [comment]
@angelyoung24 any updates on this? hoping to get this out soon

**Comment by MikeyManoguerra** [comment]
#262 done!
