### ISSUE TITLE
Add Metabase to docker

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#238]
As a user, I would like to be able to build metabase reports against the fake data created in the back end of the MVP.

Done: 
Add metabase as a service to docker file (maybe? open to other ideas)

We have a basic version of [metabase](https://github.com/CodeForPhilly/prevpoint-metabase), but it's using its own postgres instance - metabase allows us to set up a connection to the actual db within the metabase UI so the postgres in the metabase container may not be necessary.

**Comment by ThrowsException** [comment]
Is there a current metabase instance running somewhere? Why can't that connect to the prevention point database?

**Comment by mariekers** [comment]
going to host metabase separately
