### ISSUE TITLE
Seed Data for Front Desk Check In

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#24]
Generate seed data based on the [HRSC sign-in sheets](https://drive.google.com/open?id=1FXWwucFs3mtfgIR3GksoxMnCkyNyvtU4hVQSoBtkG18) (each program has a sheet).  Python with _most_ of the fields necessary is available in [drive](https://drive.google.com/open?id=1i9XPTaGXPCT1F32wyxqm1fJHJ7rrZNVw).  

Fields to add:
-seen (bool) 
-seen_datetime
-called (bool)
-called_datetime

The programs in this script correspond with the programs in the sheet.  Need to make sure that each program doesn't have more than 4-5 services available in the fake data (so mapping program -> service doesn't become insane).

**Comment by swearingbird** [comment]
Added to frontend development slack
