### ISSUE TITLE
all visits related to particpant endpoint

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#251]
`/api/participants/<id>/visits`

 this endpoint is retrieve only. do not allow post. 

This endpoint will take the participant_id and return all visits associated with them.

make sure each visit is not redundantly populated with all the visit information

**Comment by MikeyManoguerra** [comment]
look into a "fat models, skinny views method". a model method that queries by participant_id would be easy to implement and follow best practice

**Comment by MikeyManoguerra** [comment]
https://docs.djangoproject.com/en/3.0/topics/db/managers/

**Comment by alex-cots** [comment]
Should the foreign keys to Program and Service be embedded, left as foreign keys, or something else?

**Comment by MikeyManoguerra** [comment]
let's populate with `ServiceforProgramSerializer`
and `ProgramSerializer` (but leave out a nested services array)

we do not want the populated participant object, just the FK. 

Just use `viewsets.Viewset` and define `retrieve` as this is a read only endpoint

finally, you can add new classes in the `/visits/` directory files, no need to create a completely new folder
