### ISSUE TITLE
Make reusable wrappers

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#269]
- take reused components identified in #268 and turn them into reusable wrappers

Goal: Take Material-UI components used throughout the app and making them DRY.

Wrapping components should take in props
Material-UI components slated for wrapping include but not limited too:
@crsmyz  
`<h1-h5>`
`<InputLabel>`
`<Input>`

@MikeyManoguerra 
`<button>`
`<FormGroup>`
`<Typography>`
etc.

More Material-UI components may be eligible for wrapping than the ones listed above so always look for opportunities to wrap.

**Comment by MikeyManoguerra** [comment]
This round of this concept is finished. specific wrappers can get their own tickets
