### ISSUE TITLE
change urgency values

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#277]
Change "urgency" to categorical values provided by Prevention Point 

IF possible, pass text as urgency value while retaining integer in back end

**Comment by mariekers** [comment]
from high --> low (I can't remember if we made 5 or 1 the highest urgency)
crisis, urgent, brief visit, time sensitive

**Comment by MikeyManoguerra** [comment]
are there only four urgency levels? 

Or does this imply a step below 'time sensitive' that has no label

**Comment by MikeyManoguerra** [comment]
@mariekers

**Comment by mariekers** [comment]
yeah!  they're cool with 4
