### ISSUE TITLE
Higher z-index on nav bar

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#281]
the queue taps go over top of the navbar when scrolling. 

Done: give the nav bar a larger z-index.

**Comment by mariekers** [comment]
hey @thatzacdavis  would you still like to work on this?

**Comment by thatzacdavis** [comment]
Not right now, I'll take my name off

**Comment by LizKalter** [comment]
I don't see where this is happening. Can anyone confirm that this issue still exists? Thanks.

**Comment by LizKalter** [comment]
The changes in PR #342 will fix this.
