### ISSUE TITLE
change 'user' to 'participant'

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#298]
All Front End references to 'user' should become 'participant' 

- the component and File UserSearch should become ParticipantSearch

this includes but is not limited to
	- variable names
	- form field names
	- body copy/ text
	- pieces of state
	- comments

In addition: any reference to uuid or userId or user_id in the front end is  should be ppid or preventionPointId. this is PPP's id system and is one character+last four ssn.
this is NOT variables named `id` aka the database id of the user /visit/ other
In the context of this application, Users are healthcare providers using the application, "Participants" are patients/clients. The application will eventually have front end components that deal with system Users, so the incorrect naming should be handled now to avoid confusion

**Comment by crsmyz** [comment]
This is pending a PR review as well.
