### ISSUE TITLE
Frontend pre-submit form validation

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#299]
At the top of handleSubmit in the ParticipantInfo Component, we need a "validateFormFields" (or similar) function/s that can be passed the data from the mobx state. 

- validateParticpant and validateVisit can be seperate fns
- the validate function will run a series of checks. some examples could be  
	- ppid length and character type (6, numbers and letters)
	- date is reasonable birthdate for a human (born with the last ~150 years)
	- name exists 
	- other
- the function will return an object. if the object is empty, the form is cleared for submission. if the object contains errors, the error should be a key that is the name of the form field, and a value that is a short description of the error.
- if there is an error, set a mobx piece of state to error: true, and exit out of the form submission.
- do not worry about field specific error raising if that makes the ticket too big, that can be handled separately. the mobx error should raise a form level error of some kind to alert the user of the error/s.

**Comment by MikeyManoguerra** [comment]
Use form control to display errors

**Comment by sxgormley** [comment]
@crsmyz Hi Chris! What is the status of this?

**Comment by MikeyManoguerra** [comment]
see our new  yup validation in #426 #421
