### ISSUE TITLE
Prevention Point employee tables and login

### ISSUE THREAD

**Issue by bkarlovitz** [CodeForPhilly/prevention-point#3]
Define tables to store prevention point employee records and login process.

**Comment by kyle-hauber** [comment]
@bkarlovitz - Assigning to you since you created this and I believe you've already completed. If so, can you please move it to PR review or Done on our board (or at least confirm for me and I'll move)? If not, feel free to take it or unassign.

**Comment by tantanchen** [comment]
using Django users and groups
