### ISSUE TITLE
ParticipantList console errors

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#306]
Fix issues associated with two errors: 

error1: `Warning: validateDOMNesting(...): <h5> cannot appear as a child of <tbody>.`
solution: nest the 'No participants found' message in PrevPointTableBody in a cell and row. use PrevPoint typography.

error2: `Warning: React does not recognize the `showLabel` prop on a DOM element. `
I think this error is because we are using MUI's bottom navigation component, but a 3rd party nav library (react router)

suggested solution: remove the BottomNavigation component and use 
```
<Grid 
   container
   aria-label="bottomNav"
   className={classes.addParticipantNav}
> 
	<Grid item xs={12}>. // class with style display: flex, justify content center 
		<Link> ...
```

**Comment by crsmyz** [comment]
I'll take a look today

**Comment by crsmyz** [comment]
PR is in and ready for review
