### ISSUE TITLE
Reusable Handle change method

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#321]
Make "handle change" onChange method for form inputs reusable
Currently, Each form field has its own individual method. 

Update so there is a universal method that takes `e.Target` and uses `name` property and `value` property from input to update state.

See react docs:
https://reactjs.org/docs/forms.html#handling-multiple-inputs

**Comment by LizKalter** [comment]
Hello. I'm interested in working on this issue.

**Comment by MikeyManoguerra** [comment]
Awesome!

A couple of extra notes... this 'handleChange' method should replace the update type methods in the `ParticipantStore.js`, and thus you can pass less props down to the Form components like `<ParticipantForm/>`

reach out if you have any questions on what the app is doing  or how we handled something.

**Comment by LizKalter** [comment]
Looks like some tests are failing because form field name attributes changed. Should I update the tests as part of the pull request?
