### ISSUE TITLE
fix logo shrink.

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#328]
Give prevention point logo a min-width so it does not shrink on mobile:
wrap it in a react router  <Link/> tag ,that takes them to the queues page

(User will assume as such)

I anticipate this requires some reorganizing of the nav bar at mobile width. 
the "general services" button can wrap below the logo

**Comment by LizKalter** [comment]
The changes in PR #342 will fix this.
