### ISSUE TITLE
Queuestore variable name confusion

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#329]
A situation arises where `program[i].participants.participant` is the way to get to an individuals data in the queue logic.

the first 'participants' should be renamed to 'visits' to align with the backend naming.

`program[i].visits.participant`...

this is the line where to investigate:
https://github.com/CodeForPhilly/prevention-point/blob/master/frontend/src/stores/QueueStore.js#L25

**Comment by JackRyan1989** [comment]
@MikeyManoguerra As far as I can tell, the only place that needs to be changed is Line 24 of QueueStore.js https://github.com/CodeForPhilly/prevention-point/blob/master/frontend/src/stores/QueueStore.js#L24

I found no other reference to program.participants in /core or /frontend/src, am I missing something?

**Comment by MikeyManoguerra** [comment]
This is the other one. 
https://github.com/CodeForPhilly/prevention-point/blob/51b4d8a56654cbc8525b1e5f9c0cadb8d5b7c8c7/frontend/src/components/QueueComponent/QueueTable/QueueTable.js#L74
I think that is it.
