### ISSUE TITLE
update/create new models based off api contract

### ISSUE THREAD

**Issue by tantanchen** [CodeForPhilly/prevention-point#33]
GET /api/participants/
- purpose: find potential participants
- filter by first/last/dob/4ssn
- return { participants: [<participant>} }

GET /api/queue/
- purpose: show the queue for services being offered
- return { services: { service: [ service_event ] }

POST /api/visits/
- purpose: participant check-in
- for each service to be rendered, a service event is created.
- each service event has a service, and a program through the service
- return { created: true, visit_id: 1 }

POST /api/visits/1/service_events

purpose: create a new service event
type: arrived, called, seen, left
service_id: the id of the service they're here for
visit_id: inferred from url param
payload: { type: "called|seen|left|" }
return { created: true, visit_id: 1, service_event_id: 1 }
GET /api/services

purpose: return an array of open programs and services
payload: {}
return { programs: [ { id, services: [ ] } ] }

**Comment by MikeyManoguerra** [comment]
GET /api/participants/ #39 , ++
POST /api/visits/ #52
