### ISSUE TITLE
insurance name should influence 'has insurance'

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#332]
if an existing participant has insurance, the ParticipantForm should set has_insurance to true.
clicking false should set insurer to an empty string, and remove the insurance select from the DOM 

(see the way Program and Service dropdowns work on the visit form as reference)

Consider doing #321 first, as it is high priority

**Comment by LizKalter** [comment]
@MikeyManoguerra This could also be done in the new handler method inside the "is_insured" switch case. Which location is more appropriate?
