### ISSUE TITLE
Live Search on Participant List

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#336]
On The ParticipantList page, we want to add the functionality for onChange live search in a search bar. As a user starts typing a name, the participant list will filter the results.

This will be used for quick form fill outs. If a participant is waiting in line for a short service ( syringe exchange, receiving mail) 
A user can:
- filter the users
- take them to the more robust visits page
- OR, use a dropdown(?) of "quick forms" that can have a modal popup (to be determined)

This requires a bit of a redesign of the participantsList.
- keeping a persistent list of all participants in state while the app is in use
- lazy loading the rows. React will be overloaded if it has to re-render thousands of participants on every keypress

If you have ideas for this issue, please share

**Comment by LizKalter** [comment]
I'm looking into an implementation using Material UI Autocomplete. It may not meet all the requirements here, but I think it's a start.

**Comment by mariekers** [comment]
check to see if we should be avoiding the model serializer?

**Comment by MikeyManoguerra** [comment]
As discussed last week, this can delay an api call until the user enters the first few query characters. This can then use the endpoint to get a subset of participants, and continue to filter with js. if the query string gets below our threshold length, it will re request data from the api once the minimum query length is reached again
