### ISSUE TITLE
get frontdesk/participants endpoint

### ISSUE THREAD

**Issue by tantanchen** [CodeForPhilly/prevention-point#34]
GET /frontdesk/participants/
- purpose: find potential participants
- filter by first/last/dob/4ssn
- return { participants: [<participant>} }

**Comment by Nkdiaz** [comment]
I'm working on this

**Comment by Nkdiaz** [comment]
Finished the first Get request for participants and their filter. Holding off on the other ones until Tuesday.

**Comment by tantanchen** [comment]
Separated last end point into a different issue
https://github.com/CodeForPhilly/prevention-point/issues/61

**Comment by MikeyManoguerra** [comment]
#39
