### ISSUE TITLE
post api/service events endpoint

### ISSUE THREAD

**Issue by tantanchen** [CodeForPhilly/prevention-point#35]
POST /api/visits/
- purpose: participant check-in
- for each service to be rendered, a service event is created.
- each service event has a service, and a program through the service
- return { created: true, visit_id: 1 }

POST /api/visits/1/service_events
- purpose: create a new service event type: arrived, called, seen, left
service_id: the id of the service they're here for
visit_id: inferred from url param
- payload: { type: "called|seen|left|" }
- return { created: true, visit_id: 1, service_event_id: 1 }

**Comment by mattusifer** [comment]
I'm taking a look at this one today

**Comment by MikeyManoguerra** [comment]
#37 handles first endpoint
