### ISSUE TITLE
Onblur, if field is required, but empty, alert the user

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#352]
look into material uIs form control  component and onblur method

**Comment by LizKalter** [comment]
@MikeyManoguerra I think this may be more complicated than it sounds like. Just wondering if you'd like to pull in a library to handle form validation. I'm thinking maybe Formik. https://formik.org/

**Comment by MikeyManoguerra** [comment]
While that does seem like an obvious choice,
I have been resisting it because it will cause major changes to how we handle the state. 
All of our form state is in the global state. 

Without formik, we will have to keep an array of fields that contain errors, and pass them down by name to the form. 

Either way, we are going to have to write some standardized validating functions that the fields can use. I think we should decide as a group which direction we want to take.

**Comment by MikeyManoguerra** [comment]
see newer issues #406 , #408
