### ISSUE TITLE
create site table 

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#364]
Create model for sites in django

Model includes:
site_id
site_name
site_address
site_zip
created_date

**Comment by MikeyManoguerra** [comment]
Is site_id a prevention point piece of data, or a the primary key of the table

**Comment by mariekers** [comment]
Primary key

**Comment by JackRyan1989** [comment]
I have a few questions:

1. For the site_id; is the user going to supply that or do you want to auto populate it?

2. For the zip code, are we planning on accepting hyphenated 10 character strings (eg 19119-1234) or just 5 digit codes (eg 19119)?

3. For created_date; I'm thinking of setting "auto_now_add=True". This will add the date on creation, but will set editable=False and blank=True. I can remove this if we want to allow users to change the created_date field later on.

**Comment by MikeyManoguerra** [comment]
Not sure about the date. its fine for now and we can update it later. talk to @mariekers about data to seed with.
Site_id is primary key, so actually you do not need to define it, and django will make it for you

**Comment by MikeyManoguerra** [comment]
Hey, so I remembered the way to did a default date was `default=timezone.now`. see the frontdeskevent model for an example @JackRyan1989

**Comment by JackRyan1989** [comment]
@MikeyManoguerra Thanks for that suggestion. I've set the default to timezone.now.
