### ISSUE TITLE
swap disabled flag for readonly flag in participant form

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#367]
The ParticipantForm has a disabled functionality, for stopping editing of the participant unecessarily
However, it would be better to use the readonly from materialUI in this logic instead. 

- use readonly on the inputs
- update the variable name to be isReadOnly

https://github.com/CodeForPhilly/prevention-point/blob/master/frontend/src/components/ParticipantForm.js
https://material-ui.com/api/input/

**Comment by LizKalter** [comment]
There is no visual indicator when using readOnly on the input fields.

**Comment by MikeyManoguerra** [comment]
I think that's ok? My thinking was that those fields would not be edited that often. But the disabled version is a little difficult to see. Can you update the styling based upon this flag, in the input component?

**Comment by LizKalter** [comment]
It doesn't look like I can style the MUI input component based on the readonly flag. MUI doesn't modify any class names based on that attribute. It only toggles the readonly attribute on the input field itself. This does indicate that MUI doesn't think there should be any visual difference. However, another snag that just occurred to me is that readonly is not a valid attribute on radio buttons.

**Comment by MikeyManoguerra** [comment]
Ok. looks like we should close this ticket, and then alter the styling of a disabled element to be a little darker text
