### ISSUE TITLE
Site Route

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#383]
- Create a new directory `sites` that has a view and serializer. 
( a good example is FrontDeskEvent, except you only need the one serializer.)
- register the route in `urls.py`, under default router
- go to the `management/commands/users_and_groups.py` and give view permission to each group
- write a couple of tests . you will have to create fixtures. you don't have to go crazy,  get tests, and auth tests are fine
- see this test class for ex. `class UsersTests(BaseTestCase):`

finally, I should have caught this the first time, but the name of the table and model file should be `Site` and `site.py` in the singular, and not plural. please update

**Comment by JackRyan1989** [comment]
@mariekers Just FYI I'm editing the model as well here.

**Comment by JackRyan1989** [comment]
@MikeyManoguerra Hey is this route going to be accessible via the front end, or just via admin?

**Comment by MikeyManoguerra** [comment]
Frontend. by registering the route in `urls.py`, you create a REST endpoint for that.  Then the serializer/ view is the db call + route logic, respectively. We have actually been ignoring the django admin setup, and will have to circle back to `admin.py` at the end
