### ISSUE TITLE
SEP data route

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#384]
depends upon #382 

- Create a new directory `sep_data` that has a view and serializer.  do not worry about populating the data for the FKs, this will primarily be a POST endpoint at first
- register the route in `urls.py`, under default router

##### In `management/commands/users_and_groups.py`  
- give add  permission to front desk
- give add, view, and change permission to internal provider

then 
- write a couple of tests . you will have to create fixtures. 
- make sure there is a POST test

**Comment by MikeyManoguerra** [comment]
@sxgormley  this is a good example, if  you see this merged flag, its probably safe to close the issue.  There might be some times that a PR does not complete everything in an issue, so watch out for that. However, most of the time 1 issue === 1 PR, like here

**Comment by sxgormley** [comment]
How do I tell if a PR doesn't complete everything in an issue?

**Comment by sxgormley** [comment]
> @sxgormley this is a good example, if you see this merged flag, its probably safe to close the issue. There might be some times that a PR does not complete everything in an issue, so watch out for that. However, most of the time 1 issue === 1 PR, like here

How do I tell if a PR doesn't complete everything in an issue?

**Comment by MikeyManoguerra** [comment]
ideally people will tag and mention that it does. for the scope of the tickets over the next month, its pretty much safe to assume it does unless explicitly stated otherwise. 

In addition my personal opinion is that the larger half finished ticket should be closed anyway and anew smaller ticket with the rest should be opened.  But yea, feel free to close unless it says don't !
