### ISSUE TITLE
Update django admin

### ISSUE THREAD

**Issue by sxgormley** [CodeForPhilly/prevention-point#404]
​
- update `admin.py` with all current models
- check results at localhost:8000/admin

**Comment by JackRyan1989** [comment]
@MikeyManoguerra Couple of questions: 
1. For models with ForeignKeys, do I have to create inlines and add them to the models that reference those keys?
2. Should I go and make all models singular? The admin portal automatically appends an 's' to the end of each model link, so we have a few with "ss" going on.

**Comment by MikeyManoguerra** [comment]
models should be singular. If you want to update the remaining ones, go ahead, just make sure you update them across the repo, (wherever they might be used).

I think the Foreign Key might be referring to having the models populated? so. a visit would have all the participant information, not the id? 

The main goal is to have all the models represented in the back end. I am not really educated in the admin side of Django, but I assume there is lots of customization available. If you can do. a little research that would be awesome.

**Comment by mariekers** [comment]
system admin: users/groups
system objects: program, program availability, sites, services
