### ISSUE TITLE
SEP form Population

### ISSUE THREAD

**Issue by sxgormley** [CodeForPhilly/prevention-point#405]
this goes along with `Sep form` ticket. you can submit as one PR, but probably want to do this first

- remove the `edit particpant` from the participant list titles constant
- do a conditonal spread of the map fn results + 'edit particpant' or 'populate sep form' based upon the global sidebar state.
- same thing with the button in `ParticpantListTableBody.js`. make it a button that populates the SEP form. choose a different icon to represent the sep button, dealers choice.

**Comment by sxgormley** [comment]
Hey @LizKalter! How's it coming?

**Comment by LizKalter** [comment]
@sxgormley I am focused on #406 at the moment. I may add this ticket to the same PR when I get to it depending on the timing. I still need to work through some details on #406 with @MikeyManoguerra.

**Comment by MikeyManoguerra** [comment]
@sxgormley @LizKalter noted and discussed! Yes, this one is contingent on #406, so its up to liz how she mixes this one in,  during or seperately

**Comment by MikeyManoguerra** [comment]
I think this can happen seperately, as a refactor. finish the form with the current "if(length of participants === 1)" and we ca add this as a new feature @LizKalter
