### ISSUE TITLE
Fix participant list header on mobile

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#412]
This is my fault for not catching initially.
currently  the constant for header titles is: 

```

export const PARTICIPANT_LIST_TABLE_TITLES = [
  { value: true, title: "PPID" },
  { value: true, title: "First Name" },
...
]
```

however, in the map function `PrevPointTableHead.js` is  destructuring 'mobile' as a key. 
since mobile is always `undefined` and thus falsy (there is no mobile key available, only value), the every header title get the css class that hide the table on mobile, per our ternary. 

change the the name of the key from  'value' to 'mobile' for each of the objects in the `PARTICIPANT_LIST_TABLE_TITLES` array.

**Comment by sxgormley** [comment]
Hey, @dmjohnspor! How's this coming along?

**Comment by dmjohnspor** [comment]
Hello @sxgormley this issue is completed.
