### ISSUE TITLE
Global SnackBar Component:

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#420]
https://material-ui.com/components/snackbars/#snackbar

- import SnackBar and SnackBarContent  seperately in this style in App.js: 
`import Snackbar from '@material-ui/core/Snackbar';`

- define   `const participantStore = rootStore.ParticipantStore`

- place the SnackBarContent inside SnackBar below routes index component like this
```
<Snackbar
    anchorOrigin={{
      vertical: 'bottom',
      horizontal: 'right',
    }}
    open={participantStore.snackbarState.open}
    autoHideDuration={6000}
    onClose={() => participantStore.setSnackbarState('', { open: false })}
  >
    <SnackbarContent message={participantStore.snackbarState.message} />
</Snackbar>
```

- in participantStore, create a piece of state 
`snackBarState = { message: '', open: false }`

- also, add a method called `setSnackBarState`

```
setSnackBarState(message, options = { open: true }){ 
  // we setup otions like this to maybe add more later
  this.snackbarState.message = '';
  this.snackBarState.open = options.open
}
```

Finally. test it out by using it in the error handling processes we created. In createVisit, instead of throwing the error message, pass it to the setSnackBarState

**Comment by sxgormley** [comment]
Hey, @dmjohnspor how is this coming?

**Comment by dmjohnspor** [comment]
It's almost done. It's going to be ready tonight, tomorrow morning the latest

**Comment by dmjohnspor** [comment]
My bad, this issue is ready to be closed
