### ISSUE TITLE
"No participants found" display plus state access in layout

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#423]
#### Part 1:

update the `participantStore.js` files `getParticpantsMethod`  not ok block

```
  if (!ok || !data) {
        this.setParticipantsList([])
        throw new Error(status)
      }
```

Create a new component called NoResults.
it must have a:
- Grid container
- Grid item(s) (`xs={12}`)
- Prev point typography components
- prev point button

It displays a descriptive message saying  something to the effect of: 
"No participants found"
"Use the sidebar on the right to search"

pass the data in as props.
props will be: 
`heading`: string
`subheading`: string
`action`: function

This makes this component reusable, we may perhaps use it on ExistingParticipantView later.

Use this component in `views/ParticipantList.js`
if there are participants in the store (`.length`) display the Prevpoint table.
otherwise, display the no results  component, with the message passed in.
Use a ternary.

What is the action for?
---
We want to make the sidebar open state global, so we can control it in other places.

- wrap the MainLayout component in an observer (see other files for syntax)
- use `useContext` to get the root store context, then make a participant store variable. (nothing fancy here, just copy the pattern from another connected component.)
- create an `@observable` piece of state, and then move the `handleDrawer*` functions to the participantStore as methods.
- replace `open` variable and hook fn with mobx state logic in MainLayout.
- finally in ParticipantList, pass `handleDrawerOpen` to the `action` prop we created  above.

results: when there are no results from the participant endpoint, Our `NoResults` component displays. this component has a button that controls the global state  of the drawer/sidebar, and opens it when clicked. the button does not close the sidebar when clicked again.

**Comment by sxgormley** [comment]
Hey, @dmjohnspor how's this going?

**Comment by dmjohnspor** [comment]
First half of the ticket is done, today I am finishing with the second part.

**Comment by dmjohnspor** [comment]
#435 closed
