### ISSUE TITLE
test participant store actions

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#478]
https://semaphoreci.com/community/tutorials/how-to-test-react-and-mobx-with-jest

sort of like this article, the section starting "Unit Testing with Mobx"

not any of the enzyme/integration stuff, just testing the store directly

**Comment by JackRyan1989** [comment]
@MikeyManoguerra do you want me to test the flow functions as well, like getParticipants, createParticipant, getVisits etc.?
