### ISSUE TITLE
Hookup login page frontend and backend

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#48]
* token refresh that that user's aren't logged out every 5 minutes

**Comment by kyle-hauber** [comment]
@bkarlovitz - Assigning this to you based on our conversation last week, but lmk if this should go to someone else

**Comment by MikeyManoguerra** [comment]
#75 (?) i got to the search participants page

**Comment by mariekers** [comment]
hey @bkarlovitz are you working on this?

**Comment by mariekers** [comment]
Or make FE component to refresh token

**Comment by kyle-hauber** [comment]
closing story.  Logged bug ticket under #153
