### ISSUE TITLE
Python tests failing

### ISSUE THREAD

**Issue by grahamalama** [CodeForPhilly/prevention-point#59]
Python tests are currently failing. 

One reason is that there's a configuration error: [this line](https://github.com/CodeForPhilly/prevention-point/blob/45a01a11ee870369c1ac7512e3bf1b92446c39fa/core/participants/test.py#L3) should be `from core.tests.base import BaseTestCase`.

The other is that [this test](https://github.com/CodeForPhilly/prevention-point/blob/45a01a11ee870369c1ac7512e3bf1b92446c39fa/core/participants/test.py#L21) is failing.

**Comment by tantanchen** [comment]
passing tests now
