### ISSUE TITLE
Set up React app with the Django backend

### ISSUE THREAD

**Issue by bkarlovitz** [CodeForPhilly/prevention-point#6]
This is a good starting point ( via @marcelkooi )

https://www.valentinog.com/blog/tutorial-api-django-rest-react/

**Comment by grahamalama** [comment]
We can also look to [this repo](https://github.com/techiediaries/django-react) as an example. [Source](https://www.digitalocean.com/community/tutorials/how-to-build-a-modern-web-application-to-manage-customer-information-with-django-and-react-on-ubuntu-18-04)
