### ISSUE TITLE
Search Inputs on the Homepage

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#81]
**User Story**
As a front desk employee, I need to be able to search for a participant, so that I can look up their information and assign them to the queue

**Acceptance Criteria**
- [x] Search bar on the left hand side of the homepage. 
- [x] Should be able to search by UID, first name, and last name, in that order.  
- [x] All fields are optional.  User should be able to searching by PPID or First Name/Last Name.
- [x] Search Bar should be collapsible
- [x] This component should be reusable throughout the app and should not be built to be unique to the homepage
*edit*
- [x] @jkeary merge `search-participant` into `Search_Participant_81`
- [x] @robb33 write tests `Search_Participant_81`
- [x] create pr
- [x] @jkeary work on routing to go from queues view to participants view, this can be a separate pr

**Images**
Link to UX for Search Bar Expanded: https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=2%3A18

**Comment by kyle-hauber** [comment]
@robb33 - Sorry we weren't able to connect tonight!  How's this one coming along?  Can you link issue/PR to this? Just trying to understand current state.  Thanks!

**Comment by jkeary** [comment]
@robb33 I have created a branch called `Search_Participant_81` to go along with the new naming standard.  I created it from master and pulled it your `search-participant` branch.   That way you can work for however long you wish to on the `search-participant` branch to do ui changes while I work on hooking up the data.  And when you want to and are ready you can merge your stuff into mine.

**Comment by jkeary** [comment]
On `Search_Participant_81` branch the sidebar now is able to accept and validate input.  Currently I am working on putting it all together.  Right now I am working on the page redirecting from the queue screen to the search results screen.  In that redirect I am passing the validated userId and or name and having the search results page / component be the one that makes the actual call to the api.  This means that this ticket is almost complete once the redirect is working because the other component (ticket 83) will handle the actual api call.  

Once this is working and once @robb33 is satisfied with the ui work he is doing on his branch, we can merge and do a pr

**Comment by mariekers** [comment]
@robb33 is working to match the design with figma
@jkeary is connecting it with the back end

**Comment by jkeary** [comment]
Todos
[] @jkeary merge `search-participant` into `Search_Participant_81`
[] @robb33 write tests `Search_Participant_81`
[] create pr
[] @jkeary work on routing to go from queues view to participants view, this can be a separate pr

**Comment by kyle-hauber** [comment]
10.8 Notes
Next steps: Needs tests. If not updated by next week, @jkeary  to check-in and/or pair with @robb33

**Comment by mariekers** [comment]
@jkeary @robb33 just pinging to see if tests were added

**Comment by jkeary** [comment]
@robb33 is doing so on branch `Search_Participant_81`

**Comment by AkshatVas** [comment]
Hi there!  It's been 21 days since this task was last updated.

Can I get a quick update on where we are with this? I want to make sure I fully understand what's left and what our progress and blockers are.

**Comment by jkeary** [comment]
pr is out now.  I believe Robby is finishing up his tests.

**Comment by mariekers** [comment]
@robb33 how are those tests coming along?

**Comment by mariekers** [comment]
@jkeary @robb33 is this ticket ready to close?

**Comment by robb33** [comment]
> @jkeary @robb33 is this ticket ready to close?

you have a yes from me
