### ISSUE TITLE
Check-in Entry Form

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#85]
**Updates**
10/10
* Added in required fields for all the relevant sections. 
* Encountering new error message when submitting data that says "Warning: Failed prop type: The prop "value" is marked as required in "ForwardRef(SelectInput)", but its value is "undefined"."
* Merged with the Master branch and passed to James to get help resolving the error. 
* View repo at https://github.com/CodeForPhilly/prevention-point/blob/participant-info/frontend/src/components/ParticipantInfo.js

10/8 
Removed notes modal from component. Trying to get updateParticipant working. createParticipant works.

9/26
* Added field for urgency level and connected to backend.
* When page loads, card for notes is hidden. When user clicks Submit button, card will reveal and be populated with the date, selected program, and note entered in field. 
* Clicking card opens a modal displaying inputted note.
* Next Steps:  Need to display the notes modal with text box so that user can update note. Need to make it so that the date displayed uses logic to gather whatever the current date is, and automatically include it here. Need to hook getParticipant function to gather existing patient data in the Participant Info forms (still leave Check In Participant fields blank), and display all notes that have been previously written about this patient during other visits.

9/25 
* Forms are hooked up to the backend and submits a new participant in the database based on values entered in the fields upon clicking submit.
* Next steps are to add additional fields included in the latest mockup, and a notes module to the side that populates with text based on words entered in the notes field, program selected, and current date upon clicking submit. Clicking this notes module will cause a modal to appear that lets users edit the text. 
* Need to confirm that clicking submit will visually display this new participant on the ParticipantList screen. 
* Need to hook getParticipant function to ensure that clicking a participant will still show the captured information from previous entries on ParticipantInfo.
 
9/18 
* Connected with Matt and successfully set up the backend so that it can accept data on handleSubmit. Next steps are to polish forms and add remaining elements to check in participant.

9/17 
* Coordinating call with Matt and Robbee to figure out how to connect component to backend. 

**User Story:**
As a front desk employee, I need a form where I can input user information, so that they can be added to the queue.

**AC:**
This form will be used at several points within the platform: checking in participants who are new to the system, updating participant information, and adding existing participants who are already in the system
- [x]  Form should appear as a modal after clicking the add new participant button or the plus button on an existing participants row in the search results
- [x]  Need a data entry form with the following fields:
    - [x] First Name - required
    - [x]  Last Name - required
    - [x]  Date of Birth - required
    - [x]  User ID - required
    - [x]  Race - required
    - [x]  Gender - required
    - [x]  Program - required
    - [x]  Service - required
    - [x]  Insurance Status - optional
    - [x]  Insurance Provider - optional
    - [x]  Urgency level - should be a 1 - 5 selection
    - [x]  Notes field
- [x] These fields should be broken up into 2 sections: Participant Information and Check-in Information:  
- [x] For NEW participants - all fields should be blank
- [x] For EXISTING participants - The following fields should be left blank and must be selected by the front desk employee:
    - [x]  Program - required
    - [x]  Service - required
    - [x]  Urgency level - should be a 1 - 5 selection
    - [x]  Notes field
* Upon submit, the system should append a timestamp that is used to generate the Time column on the Homepage
* Upon submit, should land back on the waitlist page

**Images:**
* https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=110%3A7
* https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=59%3A15

**Comment by kyle-hauber** [comment]
@cfazio - are we keeping the urgency field?

**Comment by mariekers** [comment]
@mattusifer @jkeary are working to help @rlacon figure out how to make the back end calls for these fields

**Comment by jkeary** [comment]
it gets and posts to participant api.  

Theres some work left for @rlacon to do on the Notes section.

**Comment by mariekers** [comment]
@rlacon got any updates?

**Comment by mariekers** [comment]
@jkeary @rlacon should I assign this to someone else?  I know you're busy with your new gig, Ryan (congrats!)

**Comment by rlacon** [comment]
@mariekers thank you! Yes, could you assign someone else to this please?

**Comment by mariekers** [comment]
@rlacon are all your changes pushed to the ticket branch? 
@crsmyz  you interested in working on this?

**Comment by crsmyz** [comment]
Starting some work on this tonight.
