### ISSUE TITLE
Check to see if a service is available on a given day of the week

### ISSUE THREAD

**Issue by tantanchen** [CodeForPhilly/prevention-point#93]
Background:
We need to account for the hours that services are available. i.e. A service closes at 5pm and should no longer accept appointments. In addition, certain services are only available on certain days. i.e. Legal services are only available on Tuesdays and Thursdays. We will also need the ability to edit the days/times for all future services. 

TODO:
- define endpoint 
- finalize table structure that stores which services are available on which days

**Comment by mariekers** [comment]
@kyle-hauber - do we need a front end ticket to incorporate this into the UI?

**Comment by mariekers** [comment]
How do we mange updates to this data (they may change the availability for each program on a given day somewhat regularly)
